#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib/markdown-parser', __FILE__)
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'cli'

cli = Cli.new
cli.convert_file
